# Section: Securing Federated Learning

- Lesson 1: Trusted Aggregator
- Lesson 2: Intro to Additive Secret Sharing
- Lesson 3: Intro to Fixed Precision Encoding
- Lesson 4: Secret Sharing + Fixed Precision in PySyft
- Final Project: Federated Learning wtih Encrypted Gradient Aggregation

# Lesson: Federated Learning with a Trusted Aggregator

In the last section, we learned how to train a model on a distributed dataset using Federated Learning. In particular, the last project aggregated gradients directly from one data owner to another. 

However, while in some cases it could be ideal to do this, what would be even better is to be able to choose a neutral third party to perform the aggregation.

As it turns out, we can use the same tools we used previously to accomplish this.

# Project: Federated Learning with a Trusted Aggregator

### Step 1: Create Data Owners

In [0]:
!pip install syft

In [1]:
import syft as sy
import torch as th
from torch import nn, optim

hook = sy.TorchHook(th)

W0712 00:01:48.517171 139881662416768 secure_random.py:26] Falling back to insecure randomness since the required custom op could not be found for the installed version of TensorFlow. Fix this by compiling custom ops. Missing file was '/usr/local/lib/python3.6/dist-packages/tf_encrypted/operations/secure_random/secure_random_module_tf_1.14.0.so'
W0712 00:01:48.532685 139881662416768 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/tf_encrypted/session.py:26: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.



In [6]:
# create a couple workers

bob = sy.VirtualWorker(hook, id="bob")
alice = sy.VirtualWorker(hook, id="alice")
secure_worker = sy.VirtualWorker(hook, id="secure_worker")

# this step is important in the real-world application.
# You need to inform the workers of others existance
# you will probably have an ssh or http worker, not a virtual worker.

bob.add_workers([alice, secure_worker])
alice.add_workers([bob, secure_worker])
secure_worker.add_workers([alice, bob])

W0712 00:24:56.727229 140369910253440 base.py:628] Worker alice already exists. Replacing old worker which could cause                     unexpected behavior
W0712 00:24:56.729898 140369910253440 base.py:628] Worker secure_worker already exists. Replacing old worker which could cause                     unexpected behavior
W0712 00:24:56.731236 140369910253440 base.py:628] Worker bob already exists. Replacing old worker which could cause                     unexpected behavior
W0712 00:24:56.732010 140369910253440 base.py:628] Worker secure_worker already exists. Replacing old worker which could cause                     unexpected behavior
W0712 00:24:56.733314 140369910253440 base.py:628] Worker alice already exists. Replacing old worker which could cause                     unexpected behavior
W0712 00:24:56.734714 140369910253440 base.py:628] Worker bob already exists. Replacing old worker which could cause                     unexpected behavior


<VirtualWorker id:secure_worker #objects:0>

In [0]:
# A Toy Dataset
data = th.tensor([[0,0],[0,1],[1,0],[1,1.]], requires_grad=True)
target = th.tensor([[0],[0],[1],[1.]], requires_grad=True)

# get pointers to training data on each worker by
# sending some training data to bob and alice
bobs_data = data[0:2].send(bob)
bobs_target = target[0:2].send(bob)

alices_data = data[2:].send(alice)
alices_target = target[2:].send(alice)


### Step 2: Create the Model

In [0]:
# Iniitalize A Toy Model
model = nn.Linear(2,1)

### Step 3: Send a Copy of The Model to Alice and Bob

In [0]:
bobs_model = model.copy().send(bob) 
alices_model = model.copy().send(alice) 

bobs_opt = optim.SGD(params=bobs_model.parameters(), lr=0.1)
alices_opt = optim.SGD(params=alices_model.parameters(), lr=0.1)


### Step 4: Train Bob's and Alice's Models (in parallel)

In [11]:
for i in range(10):

    # Train Bob's Model
    bobs_opt.zero_grad()
    bobs_pred = bobs_model(bobs_data)
    bobs_loss = ((bobs_pred - bobs_target)**2).mean()
    print(bobs_loss.child)
    bobs_loss.backward()

    bobs_opt.step()
    bobs_loss = bobs_loss.get().data
    print(f'Bob loss {bobs_loss}')

    # Train Alice's Model
    alices_opt.zero_grad()
    alices_pred = alices_model(alices_data)
    alices_loss = ((alices_pred - alices_target)**2).mean()
    alices_loss.backward()

    alices_opt.step()
    alices_loss = alices_loss.get().data
    print(f'alice loss {alices_loss}')


[PointerTensor | me:54827417433 -> bob:53853671200]
Bob loss 0.10469314455986023
alice loss 0.3794238865375519
[PointerTensor | me:89579649457 -> bob:33707855224]
Bob loss 0.06931565701961517
alice loss 0.12913891673088074
[PointerTensor | me:23996632248 -> bob:81267003579]
Bob loss 0.04911819100379944
alice loss 0.053661882877349854
[PointerTensor | me:86879335940 -> bob:73757082167]
Bob loss 0.037261731922626495
alice loss 0.030011702328920364
[PointerTensor | me:23516999686 -> bob:74279820626]
Bob loss 0.03001425787806511
alice loss 0.02180398255586624
[PointerTensor | me:99137623537 -> bob:64378437307]
Bob loss 0.02533731982111931
alice loss 0.018267646431922913
[PointerTensor | me:48980763337 -> bob:71683192911]
Bob loss 0.02211567386984825
alice loss 0.016208069398999214
[PointerTensor | me:21282451240 -> bob:62917524684]
Bob loss 0.019737496972084045
alice loss 0.01467218529433012
[PointerTensor | me:76331674791 -> bob:96298583783]
Bob loss 0.017865609377622604
alice loss 0.0133

### Step 5: Send Both Updated Models to a Secure Worker

In [0]:
alices_model.move(secure_worker) # the move function iterates on all objects in alice and call send on it. NOTEICE: inline function
bobs_model.move(secure_worker)


In [9]:
secure_worker._objects # can you identify those objects in the Secure worker?

{32874823696: Parameter containing:
 tensor([[0.5501, 0.0885]], requires_grad=True),
 80420406781: Parameter containing:
 tensor([0.0370], requires_grad=True),
 87264264897: Parameter containing:
 tensor([0.3994], requires_grad=True),
 96017481938: Parameter containing:
 tensor([[ 0.3868, -0.0388]], requires_grad=True)}

### Step 6: Average The Models

In [10]:
# A pytorch trick: to set the weights: you have to either access the data[idx] 
# or wrap the set function with (with torch.no_grad():)
# below we illustrate the first way
# the next cell demonstrates the complete way:

model.weight.data[0].set_(((alices_model.weight.data + bobs_model.weight.data) / 2).get())
model.bias.data[0].set_(((alices_model.bias.data + bobs_model.bias.data) / 2).get())

tensor([0.2182])

### Step 7: The complete solution over multiple training sessions

In [12]:
iterations = 10
worker_iters = 5

for a_iter in range(iterations):

    bobs_model = model.copy().send(bob)
    alices_model = model.copy().send(alice)

    bobs_opt = optim.SGD(params=bobs_model.parameters(), lr=0.1)
    alices_opt = optim.SGD(params=alices_model.parameters(), lr=0.1)

    for wi in range(worker_iters):
        # Train Bob's Model
        bobs_opt.zero_grad()
        bobs_pred = bobs_model(bobs_data)
        bobs_loss = ((bobs_pred - bobs_target) ** 2).sum()
        bobs_loss.backward()

        bobs_opt.step()
        bobs_loss = bobs_loss.get().data

        # Train Alice's Model
        alices_opt.zero_grad()
        alices_pred = alices_model(alices_data)
        alices_loss = ((alices_pred - alices_target) ** 2).sum()
        alices_loss.backward()

        alices_opt.step()
        alices_loss = alices_loss.get().data

    alices_model.move(secure_worker)
    bobs_model.move(secure_worker)

    with th.no_grad():

        model.weight.set_(((alices_model.weight.data + bobs_model.weight.data) / 2).get())
        model.bias.set_(((alices_model.bias.data + bobs_model.bias.data) / 2).get())
    
    print("Bob:" + str(bobs_loss) + " Alice:" + str(alices_loss))

Bob:tensor(0.0346) Alice:tensor(0.0263)
Bob:tensor(0.0170) Alice:tensor(0.0080)
Bob:tensor(0.0090) Alice:tensor(0.0031)
Bob:tensor(0.0050) Alice:tensor(0.0012)
Bob:tensor(0.0029) Alice:tensor(0.0005)
Bob:tensor(0.0017) Alice:tensor(0.0002)
Bob:tensor(0.0011) Alice:tensor(6.5901e-05)
Bob:tensor(0.0007) Alice:tensor(2.1554e-05)
Bob:tensor(0.0005) Alice:tensor(5.9672e-06)
Bob:tensor(0.0003) Alice:tensor(1.1475e-06)


In [0]:
preds = model(data)
loss = ((preds - target) ** 2).mean()

In [13]:
print(preds)
print(target)
print(loss.data)

tensor([[0.0763],
        [0.0637],
        [0.9195],
        [0.9068]], grad_fn=<AddmmBackward>)
tensor([[0.],
        [0.],
        [1.],
        [1.]], requires_grad=True)
tensor(0.0063)


# Lesson: Intro to Additive Secret Sharing

While being able to have a trusted third party to perform the aggregation is certainly nice, in an ideal setting we wouldn't have to trust anyone at all. This is where Cryptography can provide an interesting alterantive. 

Specifically, we're going to be looking at a simple protocol for Secure Multi-Party Computation called Additive Secret Sharing. This protocol will allow multiple parties (of size 3 or more) to aggregate their gradients without the use of a trusted 3rd party to perform the aggregation. In other words, we can add 3 numbers together from 3 different people without anyone ever learning the inputs of any other actors.

Let's start by considering the number 5, which we'll put into a varible x

In [0]:
x = 5

Let's say we wanted to SHARE the ownership of this number between two people, Alice and Bob. We could split this number into two shares, 2, and 3, and give one to Alice and one to Bob

In [0]:
bob_x_share = 2
alice_x_share = 3

decrypted_x = bob_x_share + alice_x_share
decrypted_x

5

Note that neither Bob nor Alice know the value of x. They only know the value of their own SHARE of x. Thus, the true value of X is hidden (i.e., encrypted). 

The truly amazing thing, however, is that Alice and Bob can still compute using this value! They can perform arithmetic over the hidden value! Let's say Bob and Alice wanted to multiply this value by 2! If each of them multiplied their respective share by 2, then the hidden number between them is also multiplied! Check it out!

In [0]:
bob_x_share *= 2
alice_x_share *= 2

decrypted_x = bob_x_share + alice_x_share
decrypted_x

10

This even works for addition between two shared values!!

In [0]:
# encrypted "5"
bob_x_share = 2
alice_x_share = 3

# encrypted "7"
bob_y_share = 5
alice_y_share = 2

# encrypted 5 + 7
bob_z_share = bob_x_share + bob_y_share
alice_z_share = alice_x_share + alice_y_share

decrypted_z = bob_z_share + alice_z_share
decrypted_z

12

As you can see, we just added two numbers together while they were still encrypted ( you are the dealer, thus still can see --and know everything-- but Alice and Bob did not really know anything about the overall deal --the sum of the numbers; the secrete--)

In this case, however, to keep the secrete is not about the relaiability / integrity of the person who holds it, rather the fact that those shareholders do not know each other!!!

One small tweak - notice that since all our numbers are positive, it's possible for each share to reveal a little bit of information about the hidden value, namely, it's always greater than the share. Thus, if Bob has a share "3" then he knows that the encrypted value is at least 3.

This would be quite bad, but can be solved through a simple fix. Decryption happens by summing all the shares together MODULUS some constant.

In [0]:
x = 5

Q = 9923 # the little fix; a very large prime number

bob_x_share = 1525 # give bob a random number.. try with negatives

alice_x_share = Q - bob_x_share + x

print(f'Bob share= {bob_x_share}')
print(f'Alice share= {alice_x_share}')
print(f'Add both shares= {bob_x_share + alice_x_share}... Wrong secrete')

Bob share= 1525
Alice share= 8403
Add both shares= 9928... Wrong secrete


In [0]:
# Decryption happens by summing all the shares together MODULUS some constant

(bob_x_share + alice_x_share) % Q

5

So now, as you can see, both shares are wildly larger than the number being shared, meaning that individual shares no longer leak this inforation. However, all the properties we discussed earlier still hold! (addition, encryption, decryption, etc.)

# Project: Build Methods for Encrypt, Decrypt, and Add 

In this project, you must take the lessons we learned in the last section and write general methods for encrypt, decrypt, and add. Store shares for a variable in a tuple like so:  `x_share = (2,5,7)`

Even though normally those shares would be distributed among several workers, you can store them in ordered tuples like this for now.

In [0]:
import random

Q = 23740629843760239486723

# accepts a secrete and shares it among n_shahre, returns a tuple with n_share shares
def encrypt(x, n_share=3):
    
    shares = list()
    
    for i in range(n_share-1):
        shares.append(random.randint(0,Q))
        
    shares.append(Q - (sum(shares) % Q) + x)
    
    return tuple(shares)

  # accepts a tuple of shares and return the decrypted values
def decrypt(shares):
    return sum(shares) % Q

In [0]:
shares = encrypt(x=7, n_share=10)
shares

(15899097772522877364249,
 11367675966508840117530,
 4900233884997846532104,
 16630337867297688321351,
 6676581143161867586917,
 965082419012027105831,
 10007139259242749719591,
 2826785571199337361780,
 9849092175711078026532,
 15840493315386645811014)

In [0]:
decrypt(shares)

7

In [0]:
def add(a, b):
    c = list()
    assert(len(a) == len(b))
    for i in range(len(a)):
        c.append((a[i] + b[i]) % Q)
    return tuple(c)

In [0]:
# run this block of code multiple times, what do you notice baout x and y?

x = encrypt(5)
print(x)
y = encrypt(7)
print(y)

z = add(x,y)
decrypt(z)

(19450006935608221574999, 18583217581987782711521, 9448035169924474686931)
(18876374866682609093470, 10862363173324101889542, 17742521647513767990441)


12

# Lesson: Intro to Fixed Precision Encoding

As you may remember, our goal is to aggregate gradients using this new Secret Sharing technique. However, the protocol we've just explored in the last section uses positive integers. However, our neural network weights are NOT integers. Instead, our weights are decimals (floating point numbers).

Not a huge deal! We just need to use a fixed precision encoding, which lets us do computation over decimal numbers using integers!

In [0]:
BASE= 10  # integer numbers (normal numbers)
PRECISION= 3  # how many porecisions after the decimal point to encode
Q = 23740629843760239486723 

In [0]:
def encode(x):
    return int((x * (BASE ** PRECISION)) % Q)

def decode(x):
    return (x if x <= Q/2 else x - Q) / BASE**PRECISION

In [0]:
encode(-0.600)

9323

In [0]:
decode(9323)

-0.6

In [0]:
# run this cell multiple times and notice the changes

x = encrypt(encode(5.5))
y = encrypt(encode(5.5))
z = add(x,y)


print(f'Value of x = {x}')
print(f'Value of y = {y}')
print(f'Value of sum = {z}')
print(f'decoded sum = {decode(decrypt(z))}')

Value of x = (3415, 7020, 14911)
Value of y = (4595, 7707, 13044)
Value of sum = (8010, 4804, 8109)
decoded sum = 1.077


# Lesson: Secret Sharing + Fixed Precision in PySyft

While writing things from scratch is certainly educational, PySyft makes a great deal of this much easier for us through its abstractions.

In [16]:
# Its a good idea to restrat the environment at this point

import syft as sy
import torch as th
from torch import nn, optim

hook = sy.TorchHook(th)

# create a couple workers

bob = sy.VirtualWorker(hook, id="bob")
alice = sy.VirtualWorker(hook, id="alice")
secure_worker = sy.VirtualWorker(hook, id="secure_worker")


bob.add_workers([alice, secure_worker])
alice.add_workers([bob, secure_worker])
secure_worker.add_workers([alice, bob])

W0709 23:57:57.634224 140300690126720 hook.py:98] Torch was already hooked... skipping hooking process
W0709 23:57:57.635967 140300690126720 base.py:628] Worker alice already exists. Replacing old worker which could cause                     unexpected behavior
W0709 23:57:57.636623 140300690126720 base.py:628] Worker secure_worker already exists. Replacing old worker which could cause                     unexpected behavior
W0709 23:57:57.637216 140300690126720 base.py:628] Worker bob already exists. Replacing old worker which could cause                     unexpected behavior
W0709 23:57:57.639671 140300690126720 base.py:628] Worker secure_worker already exists. Replacing old worker which could cause                     unexpected behavior
W0709 23:57:57.640418 140300690126720 base.py:628] Worker alice already exists. Replacing old worker which could cause                     unexpected behavior
W0709 23:57:57.641894 140300690126720 base.py:628] Worker bob already exists. Replacing 

<VirtualWorker id:secure_worker #objects:44>

In [0]:
x = th.tensor([1,2,3,4,5]) ##### the following steps work for integer values only

### Secret Sharing Using PySyft

We can share using the simple` .share()` method!

In [18]:
x = x.share(bob, alice, secure_worker) # implemets additive secrete shares
x # it's a pointer to three secrete shares

(Wrapper)>[AdditiveSharingTensor]
	-> (Wrapper)>[PointerTensor | me:18739172441 -> bob:42252646690]
	-> (Wrapper)>[PointerTensor | me:38586436369 -> alice:29192263349]
	-> (Wrapper)>[PointerTensor | me:56431200602 -> secure_worker:81275037099]
	*crypto provider: me*

In [19]:
x.child

[AdditiveSharingTensor]
	-> (Wrapper)>[PointerTensor | me:18739172441 -> bob:42252646690]
	-> (Wrapper)>[PointerTensor | me:38586436369 -> alice:29192263349]
	-> (Wrapper)>[PointerTensor | me:56431200602 -> secure_worker:81275037099]
	*crypto provider: me*

In [21]:
x.child.child['alice']

(Wrapper)>[PointerTensor | me:38586436369 -> alice:29192263349]

In [0]:
bob._objects # take a look at one of the shares.. Large random numbers --encrypted

{21697835486: tensor([ 931215927921640947,  459606633707528827, 2077348708747142219,
         2518050637076306642, 2250413087966072035])}

and as you can see, Bob now has one of the shares of x! Furthermore, we can still call addition in this state, and PySyft will automatically perform the remote execution for us!

In [0]:
y = x + x
y

(Wrapper)>[AdditiveSharingTensor]
	-> (Wrapper)>[PointerTensor | me:15477851456 -> bob:77734773635]
	-> (Wrapper)>[PointerTensor | me:54003512272 -> alice:27089881245]
	-> (Wrapper)>[PointerTensor | me:22296853755 -> secure_worker:81023290460]
	*crypto provider: me*

In [0]:
bob._objects # bob has another tensor.. why?

{21697835486: tensor([ 931215927921640947,  459606633707528827, 2077348708747142219,
         2518050637076306642, 2250413087966072035]),
 77734773635: tensor([1862431855843281894,  919213267415057654, 4154697417494284438,
         5036101274152613284, 4500826175932144070])}

In [0]:
y.get() # notice that we have doubled the values on each worker!

tensor([ 2,  4,  6,  8, 10])


### Fixed Precision using PySyft

We can also convert a tensor to fixed precision using `.fix_precision()`
This is important when doing FL since the values you are sharing are decimal numbers.

**Q: what values are we sharing? what are the shared secretes?**

In [0]:
x = th.tensor([0.1, 0.2, 0.3, 0.4]) # a decimal tensor!

In [0]:
x

tensor([0.1000, 0.2000, 0.3000, 0.4000])

In [0]:
x = x.fix_prec() # call this function to encode the decimal tensor using fixed precision
x # notice that this is a tensor chain <-------

(Wrapper)>FixedPrecisionTensor>tensor([100, 200, 300, 400])

In [0]:
print(f'Type of x {type(x)}')
print(f'Type of x.child {type(x.child)}')
print(f'Type of x.child.child {type(x.child.child)}') # <-- this is how you get the data from a fixed precision tensor

Type of x <class 'syft.frameworks.torch.tensors.interpreters.native.Tensor'>
Type of x.child <class 'syft.frameworks.torch.tensors.interpreters.precision.FixedPrecisionTensor'>
Type of x.child.child <class 'syft.frameworks.torch.tensors.interpreters.native.Tensor'>


In [0]:
# to decode the previous tensor
print(x.float_prec())

tensor([0.1000, 0.2000, 0.3000, 0.4000])


In [0]:
y = x + x
y

(Wrapper)>FixedPrecisionTensor>tensor([200, 400, 600, 800])

In [0]:
y = y.float_prec()
y

tensor([0.2000, 0.4000, 0.6000, 0.8000])

### Shared Fixed Precision

And of course, we can combine the two!

In [0]:
x = th.tensor([0.1, 0.2, 0.3])

In [29]:
x = x.fix_prec().share(bob, alice)
x

(Wrapper)>FixedPrecisionTensor>(Wrapper)>[AdditiveSharingTensor]
	-> (Wrapper)>[PointerTensor | me:33134309861 -> bob:33953795218]
	-> (Wrapper)>[PointerTensor | me:21326870340 -> alice:14098839175]
	*crypto provider: me*

In [0]:
bob._objects

{1896941596: tensor([3337927225947607575, 4115017391059871510, 5758453651456544530]),
 19122572715: tensor([1981985574526026572, 2759075739638290507, 4402512000034963527]),
 21697835486: tensor([ 931215927921640947,  459606633707528827, 2077348708747142219,
         2518050637076306642, 2250413087966072035]),
 41549875499: tensor([3701295438721311877,  945318970846132605,   20024228591329413])}

In [0]:
x = x + 3

In [31]:
x.get().float_prec()

tensor([3.1000, 3.2000, 3.3000])

In [0]:
y = x + x

In [0]:
y.get().float_prec()

tensor([0.2000, 0.4000, 0.6000])

# Final Project: Federated Learning with Encrypted Gradient Aggregation

Reuse your project from the Secuered Agggregator above to train the same model using the FL appraoch, but this time use the Additive Sharing Encryption so that the participating members have access to their own models only. There is no secure aggregator in this senario. 
Include four members in this project (Alice, Bob, Ted, and Carol). 

Hint: we will *share* the model with the shareholders, do addition on the encrypted models, and then aggregate the final model locally. 

In [1]:
import syft as sy
import torch as th
from torch import nn, optim

hook = sy.TorchHook(th)

W0712 01:14:52.882865 139980261087104 secure_random.py:26] Falling back to insecure randomness since the required custom op could not be found for the installed version of TensorFlow. Fix this by compiling custom ops. Missing file was '/usr/local/lib/python3.6/dist-packages/tf_encrypted/operations/secure_random/secure_random_module_tf_1.14.0.so'
W0712 01:14:52.897067 139980261087104 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/tf_encrypted/session.py:26: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.



In [0]:
# create workers
bob = sy.VirtualWorker(hook, id="bob").add_worker(sy.local_worker)
alice = sy.VirtualWorker(hook, id="alice").add_worker(sy.local_worker)
carl = sy.VirtualWorker(hook, id="carl").add_worker(sy.local_worker)
dan = sy.VirtualWorker(hook, id="dan").add_worker(sy.local_worker)

In [0]:
# A Toy Dataset
data = th.tensor([[0,0],[0,1],[1,0],[1,1.]], requires_grad=True).fix_precision()
target = th.tensor([[0],[0],[1],[1.]], requires_grad=True).fix_precision()

data_ptr = data.share(alice, bob, carl, dan, requires_grad=True)
target_ptr = target.share(alice, bob, carl, dan, requires_grad=True)

In [0]:
# Iniitalize A Toy Model
model = nn.Linear(2,1)

In [0]:
iterations = 10
worker_iters = 5

opt = optim.SGD(params=model.parameters(), lr=0.1).fix_precision()

for a_iter in range(iterations):
    
    # Share model with workers
    model = model.fix_precision().share(alice, bob, carl, dan, requires_grad=True)

    for wi in range(worker_iters):
        opt.zero_grad()
        pred = model(data_ptr)
        loss = ((pred - target_ptr) ** 2).sum()
  
        loss.backward()
        opt.step()
        loss = loss.get().float_precision()
      
    model = model.get().float_precision()
      
    print('Weights: ' + str(model.weight.data))
    print('Bias:' + str(model.bias.data))
    print('Loss ' + str(loss.data))
     