# Section: Federated Learning

# Lesson: Introducing Federated Learning

Federated Learning is a technique for training Deep Learning models on data to which you do not have access. Basically:

Federated Learning: Instead of bringing all the data to one machine and training a model, we bring the model to the data, train it locally, and merely upload "model updates" to a central server.

Use Cases:

    - app company (Texting prediction app)
    - predictive maintenance (automobiles / industrial engines)
    - wearable medical devices
    - ad blockers / autotomplete in browsers (Firefox/Brave)
    
Challenge Description: data is distributed amongst sources but we cannot aggregated it because of:

    - privacy concerns: legal, user discomfort, competitive dynamics
    - engineering: the bandwidth/storage requirements of aggregating the larger dataset

# Lesson: Introducing / Installing PySyft

In order to perform Federated Learning, we need to be able to use Deep Learning techniques on remote machines. This will require a new set of tools. Specifically, we will use an extensin of PyTorch called PySyft.

### Install PySyft

The easiest way to install the required libraries is with [Conda](https://docs.conda.io/projects/conda/en/latest/user-guide/overview.html). Create a new environment, then install the dependencies in that environment. In your terminal:

```bash
conda create -n pysyft python=3
conda activate pysyft # some older version of conda require "source activate pysyft" instead.
conda install jupyter notebook
pip install syft
pip install numpy
```

If you have any errors relating to zstd - run the following (if everything above installed fine then skip this step):

```
pip install --upgrade --force-reinstall zstd
```

and then retry installing syft (pip install syft).

If you are using Windows, I suggest installing [Anaconda and using the Anaconda Prompt](https://docs.anaconda.com/anaconda/user-guide/getting-started/) to work from the command line. 

With this environment activated and in the repo directory, launch Jupyter Notebook:

```bash
jupyter notebook
```

and re-open this notebook on the new Jupyter server.



In [2]:
!pip install syft
!pip install numpy

In [0]:
import torch as th

In [4]:
x = th.tensor([1,2,3,4,5])
x

tensor([1, 2, 3, 4, 5])

In [0]:
y = x + x

In [6]:
print(y)

tensor([ 2,  4,  6,  8, 10])


In [7]:
import syft as sy

W0702 23:29:57.815941 140410069403520 secure_random.py:26] Falling back to insecure randomness since the required custom op could not be found for the installed version of TensorFlow. Fix this by compiling custom ops. Missing file was '/usr/local/lib/python3.6/dist-packages/tf_encrypted/operations/secure_random/secure_random_module_tf_1.14.0.so'
W0702 23:29:57.838610 140410069403520 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/tf_encrypted/session.py:26: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.



In [0]:
hook = sy.TorchHook(th)  # this line of code create an instance of th with its backend APIs modified with Syft functions

In [9]:
th.tensor([1,2,3,4,5]) # notice that Torch functionalities still behave the same

tensor([1, 2, 3, 4, 5])

# Lesson: Basic Remote Execution in PySyft

## PySyft => Remote PyTorch

The essence of Federated Learning is the ability to train models in parallel on a wide number of machines. Thus, we need the ability to tell remote machines to execute the operations required for Deep Learning.

Thus, instead of using Torch tensors - we're now going to work with **pointers** to tensors. Let me show you what I mean. First, let's create a "pretend" machine owned by a "pretend" person - we'll call him Bob.

In [0]:
bob = sy.VirtualWorker(hook, id="bob") # creates a virtual worker (a simulaion to interface to Bob machines)

In [11]:
bob._objects

{}

In [0]:
x = th.tensor([1,2,3,4,5])

In [0]:
x_ptr =  x.send(bob) # send this data to bob

In [14]:
bob._objects

{16627761438: tensor([1, 2, 3, 4, 5])}

In [15]:
x_ptr

(Wrapper)>[PointerTensor | me:23821828811 -> bob:16627761438]

In [16]:
x.location

AttributeError: ignored

In [0]:
x.id_at_location

In [0]:
x.id

In [0]:
x.owner

In [0]:
hook.local_worker

In [0]:
x = x.get()
x

In [0]:
bob._objects

# Project: Experience with Remote Tensors

In this project, I want you to .send() and .get() a tensor to TWO workers by calling .send(bob,alice). This will first require the creation of another VirtualWorker called alice.

In [0]:
# create a second Virtual worker and call it Alice


In [0]:
# 1 - create some data (a tensor)
# 2- send the data to bob and alice


In [0]:
# notice what does the send fucntion on two workers return; a multi-pointer
x_ptr

In [0]:
# what does .child on the pointer object return?
# what does .child.child on the pointer object return? 

In [0]:
# try the .get() on the pointer


In [0]:
# try the .get(sum_results=True) on your pointer


# Lesson: Introducing Remote Arithmetic

In [0]:
x = th.tensor([1,2,3,4,5]).send(bob)
y = th.tensor([1,1,1,1,1]).send(bob)

In [0]:
x # a pointer to a remote tensor located at bob

In [0]:
y # a pointer to another remote tensor located at bob

In [0]:
z = x + y # treat those tensors (i.e., x and y) as local tensors, but they are actually executed remotely
z

In [0]:
z = z.get()
z

In [0]:
z = th.add(x,y) # we can also use Torch operation on these tensors to be executed remotely
z

In [0]:
z = z.get() # yup! same results!
z

In [0]:
x = th.tensor([1.,2,3,4,5], requires_grad=True).send(bob)
y = th.tensor([1.,1,1,1,1], requires_grad=True).send(bob)

In [0]:
z = (x + y).sum()
z = z.get()
z

In [0]:
z.backward() 

In [0]:
x = x.get()

In [0]:
x

In [0]:
x.grad

# Project: Learn a Simple Linear Model

In this project, I'd like for you to create a simple linear model which will solve for the following dataset below. You should use only Variables and .backward() to do so (no optimizers or nn.Modules). 

Furthermore, you must do so with both the data and the model being located on Bob's machine.

In [0]:
import torch as th
import syft as sy

hook = sy.TorchHook(th)  
bob = sy.VirtualWorker(hook, id="bob")

bob

In [0]:
# create some toy data for our model
input_data = th.tensor([[1.,1],[0.5,1],[1,0],[0,0]], requires_grad=True).send(bob)
output_data = th.tensor([[1.],[1],[0],[0]], requires_grad=True).send(bob)

In [0]:
# send the data to bob

In [0]:
# create some linear weights and send them to bob
weights = th.tensor([[0.01],[0.01]], requires_grad = True).send(bob)

In [0]:
# create a linear model and train it on Bob's machine
# remember how to create a linear model? No? :( 
# Here's the main steps:
#    1- find a prediction
#    2- calcualte the loss (a mean square loss)
#    3- backpropogate using the backword() function
#    4- DO NOT forget to clear your gradients after updating the weights
#    weights.data.sub_(weights.grad * lr)

prediction = input_data.mm(weights)
prediction

In [0]:
lr = 0.1

for i in range(10):
  prediction = input_data.mm(weights)
  loss = ((prediction - output_data)**2).mean()
  loss.backward()
  weights.data.sub_(weights.grad * lr)
  weights.grad *= 0

  print(loss.get().data)

# Lesson: Garbage Collection and Common Errors


In [0]:
bob = bob.clear_objects() # clear the contents of a remote object

In [0]:
bob._objects

In [0]:
x = th.tensor([1,2,3,4,5]).send(bob)

In [0]:
bob._objects

In [0]:
del x  # delete the pointer to the remote object

In [0]:
bob._objects

In [0]:
x.child.garbage_collect_data  # True by default

In [0]:
x = th.tensor([1,2,3,4,5]).send(bob)

In [0]:
bob._objects

In [0]:
x = "asdf"

In [0]:
bob._objects

In [0]:
x = th.tensor([1,2,3,4,5]).send(bob)

In [0]:
x

In [0]:
bob._objects

In [0]:
x = "asdf"

In [0]:
bob._objects  # some error from Jupyter is casuing this to appear!

In [0]:
del x

In [0]:
bob._objects

In [0]:
bob = bob.clear_objects() # erase force 
bob._objects

In [0]:
for i in range(1000):
    x = th.tensor([1,2,3,4,5]).send(bob)

In [0]:
bob._objects # notice that there is only a single tensor in bob

In [0]:
x = th.tensor([1,2,3,4,5]).send(bob)
y = th.tensor([1,1,1,1,1])

In [0]:
z = x + y

In [0]:
alice = sy.VirtualWorker(hook, id="alice")
x = th.tensor([1,2,3,4,5]).send(bob)
y = th.tensor([1,1,1,1,1]).send(alice)

In [0]:
z = x + y

# Lesson: Toy Federated Learning

Let's start by training a toy model the centralized way. This is about a simple as models get. We first need:

- a toy dataset
- a model
- some basic training logic for training a model to fit the data.

In [0]:
from torch import nn, optim

In [0]:
# A Toy Dataset
data = th.tensor([[1.,1],[0,1],[1,0],[0,0]], requires_grad=True)
target = th.tensor([[1.],[1], [0], [0]], requires_grad=True)

In [0]:
# A Toy Model
model = nn.Linear(2,1)

In [0]:
opt = optim.SGD(params=model.parameters(), lr=0.1)

In [0]:
def train(iterations=10):
    for iter in range(iterations):
        opt.zero_grad()

        pred = model(data)

        loss = ((pred - target)**2).sum()

        loss.backward()

        opt.step()

        print(loss.data)
        
train()

In [0]:
# nothing was federated up to this point!

import torch as th
import syft as sy

hook = sy.TorchHook(th)  
bob = sy.VirtualWorker(hook, id="bob")
alice = sy.VirtualWorker(hook, id="alice")



In [0]:
# create local datasets at Bob and Alice
data_bob = data[0:2].send(bob)
target_bob = target[0:2].send(bob)

data_alice = data[2:4].send(alice)
target_alice = target[2:4].send(alice)

In [11]:
datasets = [(data_bob, target_bob), (data_alice, target_alice)]
datasets

[((Wrapper)>[PointerTensor | me:9274566982 -> bob:87653307261],
  (Wrapper)>[PointerTensor | me:17022837444 -> bob:69798472729]),
 ((Wrapper)>[PointerTensor | me:40752423654 -> alice:25714750206],
  (Wrapper)>[PointerTensor | me:41280839427 -> alice:32593359363])]

In [0]:
def train(iterations=1):

    model = nn.Linear(2,1)
    opt = optim.SGD(params=model.parameters(), lr=0.1)
    
    for iter in range(iterations):

        for _data, _target in datasets:

            # send model to the data
            model = model.send(_data.location)
            print(model)

            # do training on the remote machine
            opt.zero_grad()
            pred = model(_data)
            loss = ((pred - _target)**2).sum()
            loss.backward()
            opt.step()

            # get smarter model back
            model = model.get()

            print(loss.get())

In [13]:
train()

Linear(in_features=2, out_features=1, bias=True)
tensor(4.8693, requires_grad=True)
Linear(in_features=2, out_features=1, bias=True)
tensor(0.0260, requires_grad=True)


# Lesson: Advanced Remote Execution Tools

In the last section we trained a toy model using Federated Learning. We did this by calling .send() and .get() on our model, sending it to the location of training data, updating it, and then bringing it back. However, at the end of the example we realized that we needed to go a bit further to protect people privacy. Namely, we want to average the gradients BEFORE calling .get(). That way, we won't ever see anyone's exact gradient (thus better protecting their privacy!!!)

But, in order to do this, we need a few more pieces:

- use a pointer to send a Tensor directly to another worker

And in addition, while we're here, we're going to learn about a few more advanced tensor operations as well which will help us both with this example and a few in the future!

In [0]:
bob.clear_objects()
alice.clear_objects()

<VirtualWorker id:alice #objects:0>

In [0]:
x = th.tensor([1,2,3,4,5]).send(bob)

In [0]:
x = x.send(alice)

In [0]:
bob._objects

{681755396: tensor([1, 2, 3, 4, 5])}

In [0]:
alice._objects

{59232059007: (Wrapper)>[PointerTensor | alice:59232059007 -> bob:681755396]}

In [0]:
y = x + x

In [0]:
y

(Wrapper)>[PointerTensor | me:35076229352 -> alice:14700048988]

In [0]:
bob._objects

{681755396: tensor([1, 2, 3, 4, 5]), 61259427323: tensor([ 2,  4,  6,  8, 10])}

In [0]:
alice._objects

{14700048988: (Wrapper)>[PointerTensor | alice:14700048988 -> bob:61259427323],
 59232059007: (Wrapper)>[PointerTensor | alice:59232059007 -> bob:681755396]}

In [0]:
jon = sy.VirtualWorker(hook, id="jon")

In [0]:
bob.clear_objects()
alice.clear_objects()



<VirtualWorker id:alice #objects:0>

In [0]:
x = th.tensor([1,2,3,4,5]).send(bob).send(alice)
y = th.tensor([1,2,3,4,5]).send(bob).send(jon)

In [0]:
z = x + y

TensorsNotCollocatedException: ignored

In [0]:
x = x.get() # to get the data back
x

(Wrapper)>[PointerTensor | me:59854104348 -> bob:36602545298]

In [0]:
bob._objects

{36602545298: tensor([1, 2, 3, 4, 5]), 89784608003: tensor([1, 2, 3, 4, 5])}

In [0]:
alice._objects

{}

In [0]:
x = x.get()
x

tensor([1, 2, 3, 4, 5])

In [0]:
bob._objects

# Lesson: Pointer Chain Operations

In [1]:
bob.clear_objects()
alice.clear_objects()

NameError: ignored

In [0]:
x = th.tensor([1,2,3,4,5]).send(bob)

In [14]:
bob._objects

{19293683929: tensor([1, 2, 3, 4, 5])}

In [15]:
alice._objects

{69469918454: Parameter containing:
 tensor([0.1062], requires_grad=True), 92854484805: Parameter containing:
 tensor([[ 0.4030, -0.2205]], requires_grad=True)}

In [0]:
x_ptr = x.move(alice)

In [17]:
x_ptr

(Wrapper)>[PointerTensor | me:32402167942 -> alice:32402167942]

In [12]:
x

(Wrapper)>[PointerTensor | me:64852780419 -> alice:64852780419]

In [10]:
bob._objects

{}

In [11]:
alice._objects

{64852780419: tensor([1, 2, 3, 4, 5])}

In [0]:
bob.clear_objects()
alice.clear_objects()

<VirtualWorker id:alice #objects:0>

In [0]:
x = th.tensor([1,2,3,4,5]).send(bob).send(alice)

In [0]:
bob._objects

{81869613150: tensor([1, 2, 3, 4, 5])}

In [0]:
alice._objects

{99685627431: (Wrapper)>[PointerTensor | alice:99685627431 -> bob:81869613150]}

In [0]:
x

(Wrapper)>[PointerTensor | me:83688287202 -> alice:99685627431]

In [0]:
x.remote_get() # inplace operation

(Wrapper)>[PointerTensor | me:83688287202 -> alice:99685627431]

In [0]:
bob._objects

{}

In [0]:
alice._objects

{99685627431: tensor([1, 2, 3, 4, 5])}

In [0]:
x.move(bob)

(Wrapper)>[PointerTensor | me:83688287202 -> bob:83688287202]

In [0]:
x

(Wrapper)>[PointerTensor | me:83688287202 -> bob:83688287202]

In [0]:
bob._objects

{83688287202: tensor([1, 2, 3, 4, 5])}

In [0]:
alice._objects

{}

**Exercise 1:**

- Create a toy dataset
- Create a toy linear model
- Train the dataset using Federated Learning, but do not share the gradiant with the main server, instead use the move function to send the gradients to one of the participating workers, aggregate the model, then send the final model to the main server (i.e., local worker).



---


**Exercise 2:**

While exercise 1 illustrates a good example of preseving privacy in FL, we still had to expose the gradients to one of the participating workers. To avoid this limitation, you need to send the gradiants to a TRUSTED thirdparty (trusted aggregator) who will aggregate the models and then send the final model to the server (local worker). In this way, we assure that none of the participating workers can access the aggregated model!

1. create a dataset for each worker (create two)
2. create a model for each worker and train it remotely on each worker
3. send those two models using the *move()* function to a third worker
4. the third workers aggregates the two models (find their mean)
5. send the aggregated model to the main server (local worker) using the *get()* function



---

To set the weights: `model.weight.set_()`



In [1]:
# Exercise 1
import syft as sy
import torch as th
from torch import nn, optim

W0703 01:22:42.729575 139999605405568 secure_random.py:26] Falling back to insecure randomness since the required custom op could not be found for the installed version of TensorFlow. Fix this by compiling custom ops. Missing file was '/usr/local/lib/python3.6/dist-packages/tf_encrypted/operations/secure_random/secure_random_module_tf_1.14.0.so'
W0703 01:22:42.745331 139999605405568 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/tf_encrypted/session.py:26: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.



In [0]:
hook = sy.TorchHook(th)  # this line of code create an instance of th with its backend APIs modified with Syft functions

In [0]:
# create workers
bob = sy.VirtualWorker(hook, id="bob")
alice = sy.VirtualWorker(hook, id="alice")

In [0]:
# A Toy Dataset
data = th.tensor([[1.,1],[0,1],[1,0],[0,0]], requires_grad=True)
target = th.tensor([[1.],[1], [0], [0]], requires_grad=True)

In [0]:
# Send data set to remotes
data_bob = data[0:2].send(bob)
target_bob = target[0:2].send(bob)

data_alice = data[2:4].send(alice)
target_alice = target[2:4].send(alice)

In [7]:
datasets = [(data_bob, target_bob, alice), (data_alice, target_alice, bob)]
datasets[0][2]

<VirtualWorker id:alice #objects:2>

In [0]:
# Train the models at each
# worker. Pass the updated
# model to the next worker
def train(iterations=1):
    # Create model
    model = nn.Linear(2,1)
    opt = optim.SGD(params=model.parameters(), lr=0.1)
  
    # send initial model to first worker
    model = model.send(datasets[0][0].location)
    
    for iter in range(iterations):

        for _data, _target, _next_worker in datasets:
            # do training on the remote machine
            opt.zero_grad()
            pred = model(_data)
            loss = ((pred - _target)**2).mean()
            loss.backward()
            opt.step()

            # Move to next worker
            model.move(_next_worker)

            print(loss.get())
            
    # retrieve final model
    model = model.get()
    print(model.weight)

In [16]:
train(20)

tensor(3.4978, requires_grad=True)
tensor(0.0548, requires_grad=True)
tensor(1.1892, requires_grad=True)
tensor(0.1757, requires_grad=True)
tensor(0.5265, requires_grad=True)
tensor(0.2261, requires_grad=True)
tensor(0.2942, requires_grad=True)
tensor(0.2218, requires_grad=True)
tensor(0.1928, requires_grad=True)
tensor(0.1954, requires_grad=True)
tensor(0.1388, requires_grad=True)
tensor(0.1642, requires_grad=True)
tensor(0.1050, requires_grad=True)
tensor(0.1349, requires_grad=True)
tensor(0.0816, requires_grad=True)
tensor(0.1097, requires_grad=True)
tensor(0.0642, requires_grad=True)
tensor(0.0888, requires_grad=True)
tensor(0.0509, requires_grad=True)
tensor(0.0717, requires_grad=True)
tensor(0.0405, requires_grad=True)
tensor(0.0579, requires_grad=True)
tensor(0.0322, requires_grad=True)
tensor(0.0467, requires_grad=True)
tensor(0.0257, requires_grad=True)
tensor(0.0377, requires_grad=True)
tensor(0.0205, requires_grad=True)
tensor(0.0305, requires_grad=True)
tensor(0.0164, requi



**Exercise 2:**

While exercise 1 illustrates a good example of preseving privacy in FL, we still had to expose the gradients to one of the participating workers. To avoid this limitation, you need to send the gradiants to a TRUSTED thirdparty (trusted aggregator) who will aggregate the models and then send the final model to the server (local worker). In this way, we assure that none of the participating workers can access the aggregated model!

1. create a dataset for each worker (create two)
2. create a model for each worker and train it remotely on each worker
3. send those two models using the *move()* function to a third worker
4. the third workers aggregates the two models (find their mean)
5. send the aggregated model to the main server (local worker) using the *get()* function



---

To set the weights: `model.weight.set_()`

In [0]:
# create workers
bob = sy.VirtualWorker(hook, id="bob")
alice = sy.VirtualWorker(hook, id="alice")
secureWorker = sy.VirtualWorker(hook, id="secure")

In [38]:
# Make each worker aware of the other workers
bob.add_workers([alice,secureWorker])
alice.add_workers([bob,secureWorker])
secureWorker.add_workers([bob, alice])

W0703 01:25:35.188226 139999605405568 base.py:628] Worker alice already exists. Replacing old worker which could cause                     unexpected behavior
W0703 01:25:35.189891 139999605405568 base.py:628] Worker secure already exists. Replacing old worker which could cause                     unexpected behavior
W0703 01:25:35.191916 139999605405568 base.py:628] Worker bob already exists. Replacing old worker which could cause                     unexpected behavior
W0703 01:25:35.193211 139999605405568 base.py:628] Worker secure already exists. Replacing old worker which could cause                     unexpected behavior
W0703 01:25:35.194693 139999605405568 base.py:628] Worker bob already exists. Replacing old worker which could cause                     unexpected behavior
W0703 01:25:35.198744 139999605405568 base.py:628] Worker alice already exists. Replacing old worker which could cause                     unexpected behavior


<VirtualWorker id:secure #objects:16>

In [0]:
# A Toy Dataset
data = th.tensor([[1.,1],[0,1],[1,0],[0,0]], requires_grad=True)
target = th.tensor([[1.],[1], [0], [0]], requires_grad=True)

In [0]:
# create a linear model at local worker
model = nn.Linear(2,1)

In [0]:
# Send copies of the linear model to alice and bob
model_bob = model.copy().send(bob)
model_alice = model.copy().send(alice)
aggregator = th.zeros(model.weight.shape).send(secureWorker)

In [0]:
# Create optimizers for remote workers
opt_bob = optim.SGD(params=model_bob.parameters(), lr=0.1)
opt_alice = optim.SGD(params=model_alice.parameters(), lr=0.1)

In [0]:
# Send data set to remotes
data_bob = data[0:2].send(bob)
target_bob = target[0:2].send(bob)

data_alice = data[2:4].send(alice)
target_alice = target[2:4].send(alice)

In [0]:
datasets = [(data_bob, target_bob, model_bob, opt_bob), (data_alice, target_alice, model_alice, opt_alice)]

In [0]:
# Train model on each train worker
# Move trained models to secure worker
# Aggregate and get to local
def train():
      global aggregator 
      global secureWorker
      global model
    
      # Train
      for _data, _target, _model, _opt in datasets:

          # do training on the remote machine
          _opt.zero_grad()
          pred = _model(_data)
          loss = ((pred - _target)**2).mean()
          loss.backward()
          _opt.step()

          # move trained model to secure
          _model.move(secureWorker)
          
          # Add to aggregator
          aggregator += _model.weight

          print(loss.get())  
          
      # Calculate mean
      aggregator /= len(datasets)
      
      aggregator = aggregator.get()
      
      print(aggregator.data)
      
      model.weight.requires_grad = False
      
      model.weight.set_(aggregator)
      
      model.weight.requires_grad = True
      
    

In [46]:
train()

tensor(0.5798, requires_grad=True)
tensor(0.0409, requires_grad=True)
tensor([[-0.1605,  0.4921]])
